# Generated by Django 5.2.16 on 2026-08-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achats_fournisseurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="is_invoiced",
            field=models.BooleanField(default=False, verbose_name="Facturée"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="supplier_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="achats_fournisseurs.supplierinvoice",
                verbose_name="Facture associée",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="achats_fournisseurs.receipt",
                verbose_name="Réception associée",
            ),
        ),
    ]
