# Generated by Django 5.2.16 on 2026-07-31 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achats_fournisseurs", "0001_initial"),
        ("tresorerie", "0004_alter_frais_montant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="caisse_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receptions_sortantes",
                to="tresorerie.caisse",
                verbose_name="Caisse de décaissement",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="compte_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receptions_sortantes",
                to="tresorerie.comptebancaire",
                verbose_name="Compte bancaire de décaissement",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="montant_decaissement",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Montant décaissé",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="mouvement_tresorerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reception_associee",
                to="tresorerie.mouvementtresorerie",
                verbose_name="Mouvement de trésorerie associé",
            ),
        ),
    ]
