# Generated by Django 5.2.16 on 2026-08-06 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "achats_fournisseurs",
            "0002_receipt_is_invoiced_receipt_supplier_invoice_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierinvoice",
            name="receipt",
        ),
    ]
