# Generated by Django 5.2.16 on 2026-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achats_fournisseurs", "0003_remove_supplierinvoice_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierinvoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant HT"
            ),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total TTC"
            ),
        ),
    ]
