# Generated by Django 5.2.16 on 2026-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achats_fournisseurs", "0004_alter_supplierinvoice_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="auto_invoice",
            field=models.BooleanField(
                default=True, verbose_name="Créer facture automatiquement"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="auto_invoice_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="N° Facture auto"
            ),
        ),
    ]
