# Generated by Django 5.2.16 on 2026-08-06 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "achats_fournisseurs",
            "0005_receipt_auto_invoice_receipt_auto_invoice_number",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasereturnline",
            options={
                "verbose_name": "Ligne de retour",
                "verbose_name_plural": "Lignes de retour",
            },
        ),
    ]
