# Generated by Django 5.2.16 on 2026-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etablissement",
            name="telephone",
        ),
        migrations.AddField(
            model_name="etablissement",
            name="telephone1",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone principal"
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="telephone2",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
