# Generated by Django 5.2.16 on 2026-08-17 17:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lignevente",
            options={
                "ordering": ["id"],
                "verbose_name": "Ligne de vente",
                "verbose_name_plural": "Lignes de vente",
            },
        ),
        migrations.AddField(
            model_name="lignevente",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lignevente",
            name="price_type",
            field=models.CharField(
                choices=[("detail", "Prix de détail"), ("gros", "Prix de gros")],
                default="detail",
                max_length=20,
                verbose_name="Type de prix utilisé",
            ),
        ),
        migrations.AddField(
            model_name="lignevente",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Remise",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produits_stocks.lot",
                verbose_name="Lot",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="produits_stocks.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="ventes_clients.vente",
                verbose_name="Vente",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Taux de TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Total ligne",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
            ),
        ),
    ]
