# Generated by Django 5.2.16 on 2026-07-31 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0004_alter_frais_montant_and_more"),
        ("ventes_clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="caisse_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_entrants",
                to="tresorerie.caisse",
                verbose_name="Caisse de destination",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="compte_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_entrants",
                to="tresorerie.comptebancaire",
                verbose_name="Compte bancaire de destination",
            ),
        ),
    ]
