# Generated by Django 5.2.16 on 2026-08-22 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ventes_clients",
            "0002_alter_lignevente_options_lignevente_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
        migrations.RemoveField(
            model_name="client",
            name="commercial_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="client",
            name="country",
        ),
        migrations.RemoveField(
            model_name="client",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="client",
            name="current_balance",
        ),
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="client",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="client",
            name="payment_terms",
        ),
        migrations.RemoveField(
            model_name="client",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="client",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="client",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="client",
            name="total_orders",
        ),
        migrations.RemoveField(
            model_name="client",
            name="total_purchases",
        ),
        migrations.RemoveField(
            model_name="client",
            name="website",
        ),
    ]
