# Generated by Django 5.2.16 on 2026-09-06 23:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ventes_clients",
            "0003_remove_client_city_remove_client_commercial_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Solde disponible",
                    ),
                ),
                (
                    "total_deposits",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total des dépôts",
                    ),
                ),
                (
                    "total_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total utilisé",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Wallet actif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="ventes_clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Porte-monnaie client",
                "verbose_name_plural": "Porte-monnaie clients",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "Crédit"), ("debit", "Débit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("deposit", "Dépôt en espèces"),
                            ("payment", "Paiement facture"),
                            ("avoir", "Avoir commercial"),
                            ("refund", "Remboursement"),
                            ("transfer", "Transfert"),
                            ("adjustment", "Ajustement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Solde après transaction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ventes_clients.clientwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction wallet",
                "verbose_name_plural": "Transactions wallet",
                "ordering": ["-created_at"],
            },
        ),
    ]
