# Generated by Django 5.2.16 on 2026-09-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes_clients", "0005_alter_wallettransaction_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("card", "Carte bancaire"),
                    ("check", "Chèque"),
                    ("transfer", "Virement"),
                    ("mobile_money", "Mobile Money"),
                    ("credit", "Crédit"),
                    ("wallet", "Porte-monnaie électronique"),
                ],
                max_length=20,
            ),
        ),
    ]
