# Generated by Django 5.2.16 on 2026-09-17 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes_clients", "0006_alter_paiement_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avoir",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "Avoir",
                "verbose_name_plural": "Avoirs",
            },
        ),
        migrations.AddField(
            model_name="avoir",
            name="restore_stock",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le stock a été restauré suite à cet avoir",
                verbose_name="Stock restauré",
            ),
        ),
        migrations.AddField(
            model_name="avoir",
            name="stock_restored_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de restauration du stock"
            ),
        ),
        migrations.AddField(
            model_name="avoir",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="avoir_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Numéro d'avoir"
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avoirs",
                to="ventes_clients.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avoirs_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes internes"),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="reason",
            field=models.TextField(
                help_text="Motif de l'avoir (retour, remboursement, etc.)",
                verbose_name="Raison",
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avoirs",
                to="ventes_clients.vente",
                verbose_name="Vente associée",
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="type",
            field=models.CharField(
                choices=[
                    ("refund", "Remboursement"),
                    ("return", "Retour de marchandise"),
                    ("discount", "Remise / Geste commercial"),
                    ("error", "Erreur de facturation"),
                ],
                default="refund",
                max_length=20,
                verbose_name="Type d'avoir",
            ),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(
                fields=["avoir_number"], name="ventes_clie_avoir_n_232d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(
                fields=["client", "-date"], name="ventes_clie_client__ad7733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(fields=["type"], name="ventes_clie_type_df10a7_idx"),
        ),
    ]
