# Generated by Django 5.2.16 on 2026-09-18 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0007_alter_avoir_options_avoir_restore_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avoir",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Montant total"
            ),
        ),
        migrations.CreateModel(
            name="LigneAvoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantité retournée",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total ligne",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "avoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes_clients.avoir",
                        verbose_name="Avoir",
                    ),
                ),
                (
                    "ligne_vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_avoir",
                        to="ventes_clients.lignevente",
                        verbose_name="Ligne de vente d'origine",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_avoir",
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'avoir",
                "verbose_name_plural": "Lignes d'avoir",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["avoir", "product"],
                        name="ventes_clie_avoir_i_2105bd_idx",
                    )
                ],
            },
        ),
    ]
