# Generated by Django 5.2.16 on 2026-09-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0008_alter_avoir_amount_ligneavoir"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ligneavoir",
            name="ventes_clie_avoir_i_2105bd_idx",
        ),
        migrations.AlterField(
            model_name="ligneavoir",
            name="avoir",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="ventes_clients.avoir",
            ),
        ),
        migrations.AlterField(
            model_name="ligneavoir",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ligneavoir",
            name="ligne_vente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lignes_avoir",
                to="ventes_clients.lignevente",
            ),
        ),
        migrations.AlterField(
            model_name="ligneavoir",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ligneavoir",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_avoir",
                to="produits_stocks.product",
            ),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(fields=["sale"], name="ventes_clie_sale_id_28f010_idx"),
        ),
    ]
