# Generated by Django 5.2.16 on 2026-09-29 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produits_stocks", "0001_initial"),
        (
            "ventes_clients",
            "0009_remove_ligneavoir_ventes_clie_avoir_i_2105bd_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatistiquesStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "total_ventes_carburant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total ventes carburant (FCFA)",
                    ),
                ),
                (
                    "total_litres_vendus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total litres vendus",
                    ),
                ),
                (
                    "total_ventes_services",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total ventes services (FCFA)",
                    ),
                ),
                (
                    "total_ca",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Chiffre d'affaires total",
                    ),
                ),
                (
                    "total_paiements",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total encaissements",
                    ),
                ),
                (
                    "nb_ventes_carburant",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre ventes carburant"
                    ),
                ),
                (
                    "nb_ventes_services",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre ventes services"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statistiques station",
                "verbose_name_plural": "Statistiques station",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Cuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code cuve"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la cuve"),
                ),
                (
                    "type_carburant",
                    models.CharField(
                        choices=[
                            ("essence", "Essence"),
                            ("diesel", "Diesel"),
                            ("gpl", "GPL"),
                            ("ethanol", "Ethanol"),
                            ("e10", "E10"),
                            ("e85", "E85"),
                        ],
                        max_length=20,
                        verbose_name="Type de carburant",
                    ),
                ),
                (
                    "capacite_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Capacité maximale (L)",
                    ),
                ),
                (
                    "capacite_alerte",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=12,
                        verbose_name="Seuil d'alerte (L)",
                    ),
                ),
                (
                    "niveau_actuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Niveau actuel (L)",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Emplacement"
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Cuve active"),
                ),
                (
                    "derniere_livraison",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière livraison"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuves_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuves",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuve",
                "verbose_name_plural": "Cuves",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="MouvementCuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("approvisionnement", "Approvisionnement"),
                            ("vente", "Vente"),
                            ("transfert", "Transfert entre cuves"),
                            ("ajustement", "Ajustement de stock"),
                            ("fuite", "Fuite / Perte"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Quantité (L)"
                    ),
                ),
                (
                    "ancien_niveau",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Niveau avant"
                    ),
                ),
                (
                    "nouveau_niveau",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Niveau après"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_cuve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="station_services.cuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de cuve",
                "verbose_name_plural": "Mouvements de cuve",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pompe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code pompe"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la pompe"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "En maintenance"),
                            ("panne", "En panne"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "prix_litre",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix au litre (FCFA)",
                    ),
                ),
                (
                    "compteur_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Compteur initial (L)",
                    ),
                ),
                (
                    "compteur_actuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Compteur actuel (L)",
                    ),
                ),
                (
                    "total_ventes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total vendu (L)",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Emplacement"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Pompe active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pompes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pompes",
                        to="station_services.cuve",
                        verbose_name="Cuve associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pompe",
                "verbose_name_plural": "Pompes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="MouvementPompe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("vente", "Vente"),
                            ("ajustement", "Ajustement"),
                            ("transfert", "Transfert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Quantité (L)"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant (FCFA)",
                    ),
                ),
                (
                    "ancien_compteur",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Compteur avant"
                    ),
                ),
                (
                    "nouveau_compteur",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Compteur après"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_pompe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pompe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="station_services.pompe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de pompe",
                "verbose_name_plural": "Mouvements de pompe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrixCarburant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_litre",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix au litre (FCFA)",
                    ),
                ),
                (
                    "date_application",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'application",
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Prix actif"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prix_carburant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prix",
                        to="station_services.cuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prix du carburant",
                "verbose_name_plural": "Historique des prix",
                "ordering": ["-date_application"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code service"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du service"),
                ),
                (
                    "type_service",
                    models.CharField(
                        choices=[
                            ("lavage_manuel", "Lavage manuel"),
                            ("lavage_auto", "Lavage automatique"),
                            ("gonflage", "Gonflage des pneus"),
                            ("vidange", "Vidange"),
                            ("graissage", "Graissage"),
                            ("autre", "Autre service"),
                        ],
                        max_length=20,
                        verbose_name="Type de service",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix (FCFA)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duree_estimee",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Durée estimée en minutes",
                        verbose_name="Durée estimée (min)",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Service actif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="VenteCarburant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_vente",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° vente"
                    ),
                ),
                (
                    "type_vente",
                    models.CharField(
                        choices=[("client", "Client"), ("interne", "Interne")],
                        default="client",
                        max_length=20,
                        verbose_name="Type de vente",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Quantité (L)"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix unitaire (FCFA/L)",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant total (FCFA)",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "montant_net",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant net"
                    ),
                ),
                (
                    "type_paiement",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("carte_carburant", "Carte carburant"),
                            ("wallet", "Porte-monnaie"),
                            ("credit", "Crédit"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence paiement"
                    ),
                ),
                ("est_paye", models.BooleanField(default=False, verbose_name="Payé")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "date_vente",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de vente"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes_carburant",
                        to="ventes_clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes_carburant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes_carburant",
                        to="ventes_clients.facture",
                    ),
                ),
                (
                    "pompe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes",
                        to="station_services.pompe",
                        verbose_name="Pompe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente de carburant",
                "verbose_name_plural": "Ventes de carburant",
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="VenteService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_vente",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° vente"
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant total"
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "montant_net",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant net"
                    ),
                ),
                (
                    "type_paiement",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("carte_carburant", "Carte carburant"),
                            ("wallet", "Porte-monnaie"),
                            ("credit", "Crédit"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                ("est_paye", models.BooleanField(default=False, verbose_name="Payé")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "date_vente",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de vente"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services_achetes",
                        to="ventes_clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services_vendus",
                        to="ventes_clients.facture",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to="station_services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente de service",
                "verbose_name_plural": "Ventes de services",
                "ordering": ["-date_vente"],
            },
        ),
    ]
