# Generated by Django 5.2.16 on 2026-08-05 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Catégorie de budget",
                "verbose_name_plural": "Catégories de budget",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("annuel", "Annuel"),
                            ("trimestriel", "Trimestriel"),
                            ("mensuel", "Mensuel"),
                            ("projet", "Projet"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant total"
                    ),
                ),
                (
                    "montant_utilise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant utilisé",
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant restant",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_prevu",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant prévu"
                    ),
                ),
                (
                    "montant_utilise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant utilisé",
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant restant",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="finances.budget",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.budgetcategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de budget",
                "verbose_name_plural": "Lignes de budget",
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="categories",
            field=models.ManyToManyField(
                through="finances.BudgetLigne",
                to="finances.budgetcategorie",
                verbose_name="Catégories",
            ),
        ),
        migrations.CreateModel(
            name="CompteComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de compte"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du compte")),
                (
                    "nom_complet",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom complet"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("passif", "Passif"),
                            ("capitaux", "Capitaux propres"),
                            ("produits", "Produits"),
                            ("charges", "Charges"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("1", "Classe 1 - Capital"),
                            ("2", "Classe 2 - Immobilisations"),
                            ("3", "Classe 3 - Stocks"),
                            ("4", "Classe 4 - Tiers"),
                            ("5", "Classe 5 - Trésorerie"),
                            ("6", "Classe 6 - Charges"),
                            ("7", "Classe 7 - Produits"),
                            ("8", "Classe 8 - Comptes de régularisation"),
                        ],
                        max_length=20,
                        verbose_name="Classe",
                    ),
                ),
                (
                    "niveau",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Niveau hiérarchique"
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "is_analytique",
                    models.BooleanField(
                        default=False, verbose_name="Compte analytique"
                    ),
                ),
                (
                    "is_budgetaire",
                    models.BooleanField(
                        default=False, verbose_name="Compte budgétaire"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_imported",
                    models.BooleanField(default=False, verbose_name="Importé"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="finances.comptecomptable",
                        verbose_name="Compte parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte comptable",
                "verbose_name_plural": "Comptes comptables",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationFinanciere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "devise_symbole",
                    models.CharField(
                        default="CFA", max_length=5, verbose_name="Symbole devise"
                    ),
                ),
                (
                    "exercice_debut",
                    models.DateField(verbose_name="Début de l'exercice"),
                ),
                ("exercice_fin", models.DateField(verbose_name="Fin de l'exercice")),
                (
                    "taxe_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name="TVA par défaut (%)",
                    ),
                ),
                (
                    "arrondi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de décimales"
                    ),
                ),
                (
                    "auto_validation",
                    models.BooleanField(
                        default=False,
                        verbose_name="Validation automatique des écritures",
                    ),
                ),
                (
                    "budget_alerte",
                    models.PositiveIntegerField(
                        default=80, verbose_name="Alerte budget (%)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration financière",
                "verbose_name_plural": "Configurations financières",
            },
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("fournitures", "Fournitures de bureau"),
                            ("utilities", "Services publics"),
                            ("loyer", "Loyer"),
                            ("salaires", "Salaires"),
                            ("marketing", "Marketing et publicité"),
                            ("transport", "Transport et déplacements"),
                            ("maintenance", "Maintenance et réparation"),
                            ("formation", "Formation"),
                            ("informatique", "Informatique"),
                            ("telecommunication", "Télécommunication"),
                            ("frais_bancaires", "Frais bancaires"),
                            ("impots", "Impôts et taxes"),
                            ("assurance", "Assurance"),
                            ("frais_professionnels", "Frais professionnels"),
                            ("achat_stock", "Achat de stock"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="TVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total TTC"
                    ),
                ),
                ("date_depense", models.DateField(verbose_name="Date de la dépense")),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mode de paiement"
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence paiement"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "supplier_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Fournisseur"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du fournisseur"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("paye", "Payé"),
                            ("annule", "Annulé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="depenses/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "tresorerie_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Trésorerie"
                    ),
                ),
                (
                    "ecriture_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Écriture comptable"
                    ),
                ),
                (
                    "purchase_order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Bon de commande"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approuve_le", models.DateTimeField(blank=True, null=True)),
                (
                    "approuve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses_approuvees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date_depense"],
            },
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° d'écriture"
                    ),
                ),
                ("date_ecriture", models.DateField(verbose_name="Date d'écriture")),
                (
                    "date_comptable",
                    models.DateField(auto_now_add=True, verbose_name="Date comptable"),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Taxe"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total TTC"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vente", "Vente"),
                            ("achat", "Achat"),
                            ("paiement_client", "Paiement client"),
                            ("paiement_fournisseur", "Paiement fournisseur"),
                            ("recette", "Recette"),
                            ("depense", "Dépense"),
                            ("tresorerie", "Trésorerie"),
                            ("regularisation", "Régularisation"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "vente_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID Vente"),
                ),
                (
                    "facture_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Facture client"
                    ),
                ),
                (
                    "paiement_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Paiement client"
                    ),
                ),
                (
                    "supplier_invoice_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Facture fournisseur"
                    ),
                ),
                (
                    "purchase_order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Bon de commande"
                    ),
                ),
                (
                    "supplier_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Fournisseur"
                    ),
                ),
                (
                    "client_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Client"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "compte_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecritures_credit",
                        to="finances.comptecomptable",
                        verbose_name="Compte crédit",
                    ),
                ),
                (
                    "compte_debit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecritures_debit",
                        to="finances.comptecomptable",
                        verbose_name="Compte débit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "ordering": ["-date_ecriture"],
            },
        ),
        migrations.CreateModel(
            name="RapportFinancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bilan", "Bilan comptable"),
                            ("compte_resultat", "Compte de résultat"),
                            ("tresorerie", "Tableau de trésorerie"),
                            ("budget", "Suivi budgétaire"),
                            ("ventes", "Rapport de ventes"),
                            ("depenses", "Rapport de dépenses"),
                            ("achats", "Rapport d'achats"),
                            ("client", "Rapport client"),
                            ("fournisseur", "Rapport fournisseur"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du rapport"),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "contenu",
                    models.JSONField(blank=True, default=dict, verbose_name="Contenu"),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rapports/",
                        verbose_name="Fichier",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport financier",
                "verbose_name_plural": "Rapports financiers",
                "ordering": ["-created_at"],
            },
        ),
    ]
