# Generated by Django 5.2.16 on 2026-08-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("tresorerie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mouvements_tresorerie",
                to="produits_stocks.warehouse",
                verbose_name="Entrepôt/Magasin",
            ),
        ),
    ]
