# Generated by Django 5.2.16 on 2026-07-31 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="date_valeur",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de valeur"
            ),
        ),
        migrations.AlterField(
            model_name="tresoreriejournaliere",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
    ]
