# Generated by Django 5.2.16 on 2026-07-31 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0002_alter_mouvementtresorerie_date_valeur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frais",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Montant",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Montant",
            ),
        ),
    ]
