# Generated by Django 5.2.16 on 2026-07-31 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0003_alter_frais_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frais",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="date_valeur",
            field=models.DateField(verbose_name="Date de valeur"),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant",
            ),
        ),
        migrations.AlterField(
            model_name="tresoreriejournaliere",
            name="date",
            field=models.DateField(unique=True, verbose_name="Date"),
        ),
    ]
